.TH slapt-src 8 2011-01-06

.SH NAME
slapt-src \- slackbuild utility

.SH SYNOPSIS
.B slapt-src
[\fIOPTION\fR]... [\fIACTION\fR]
.LP
.B options:
\fB--yes\fR|\fB-y\fR,
\fB--config\fR|\fB-c\fR \fIFILE\fR,
\fB--no-dep\fR|\fB-n\fR,
\fB--postprocess\fR|\fB-p\fr
.LP
.B actions:
\fB--update\fR|\fB-u\fR,
\fB--list\fR|\fB-l\fR,
\fB--clean\fR|\fB-e\fR,
\fB--search\fR|\fB-s\fR,
\fB--show\fR|\fB-w\fR,
\fB--install\fR|\fB-i\fR,
\fB--build\fR|\fB-b\fR,
\fB--fetch\fR|\fB-f\fR

.SH DESCRIPTION
.B slapt-src
is a utility to make querying, retrieving, and building slackbuilds
as easy as working with binary packages with \fBslapt-get\fR.

.SH OPTIONS
.TP
\fB\-\-yes\fR, \fB\-y\fR
Do not prompt.
.TP
\fB\-\-config\fR, \fB\-c\fR \fIFILE\fR
Use the specified configuration file instead of \fI/etc/slapt-get/slapt-srcrc\fR.
.TP
\fB\-\-no\-dep\fR, \fB\-n\fR
Do not look for dependencies.
.TP
\fB\-\-postprocess\fR, \fB\-p\fR \fICOMMAND\fR
Run specified command on generated package after the package is created.
This is handy for transforming packages into SLAX/Linux-Live modules using
the various *2lzm utilities.

.SH ACTIONS
.TP
\fB\-\-update\fR, \fB\-u\fR
Update the local cache of remote slackbuilds.
.TP
\fB\-\-list\fR, \fB\-l\fR
List available slackbuilds from enabled remote slackbuild sources.
.TP
\fB\-\-clean\fR, \fB\-e\fR
Clean out the build directories for prior built slackbuilds.
.TP
\fB\-\-search\fR, \fB\-s\fR \fIexpression\fR...
Search available slackbuilds from enabled remote slackbuild sources.
.TP
\fB\-\-show\fR, \fB\-w\fR \fIname\fR...
Show information about specified slackbuilds.
.TP
\fB\-\-install\fR, \fB\-i\fR \fIname\fR...
Fetch, build, and install the specified slackbuilds.  The named slackbuilds
can be postfixed by a colon followed by a version string to specify the exact
version if multiple versions are available.  For example, given \fIfoo-1.0\fR and
\fIfoo-1.2\fR, specifying \fIfoo:1.2\fR specifies the preference for the later.
.TP
\fB\-\-build\fR, \fB\-b\fR \fIname\fR...
Only fetch and build the specified slackbuilds.
.TP
\fB\-\-fetch\fR, \fB\-f\fR \fIname\fR...
Only fetch the specified slackbuilds.

.SH CONFIGURATION
.B slapt-src
checks The configuration file \fI/etc/slapt-get/slapt-srcrc\fR for options and
slackbuild locations.

Each slackbuild location is defined with a \fBSOURCE\fR token.

The default package file extension is defined by specifying the \fBPKGEXT\fR token.

The default package tag can be set by specifying the \fBPKGTAG\fR token.

An example configuration file may look like this:
.in +4n
.nf
.sp
# sample slapt-getrc
SOURCE=http://www.slackware.org.uk/slackbuilds.org/13.1/
BUILDDIR=/tmp
PKGEXT=txz
PKGTAG=me
.fi
.in

.SH AUTHOR
Jason Woodward <woodwardj@jaos.org>

.SH "SEE ALSO"
.BR installpkg (8),
.BR makepkg (8),
.BR pkgtool (8),
.BR upgradepkg (8),
.BR slapt-get (8)
