.\" -*- nroff -*-
.ds g \" empty
.ds G \" empty
.\" Like TP, but if specified indent is more than half
.\" the current line-length - indent, use the default indent.
.de Tp
.ie \\n(.$=0:((0\\$1)*2u>(\\n(.lu-\\n(.iu)) .TP
.el .TP "\\$1"
..
.TH slapt-src 8 
.SH NAME
slapt-src \- slackbuild utility
.SH SYNOPSIS
.B slapt-src
[
.BI option(s)
]
[
.BI action
]
.LP
.B options:
[
.B --yes | -y
]
[
.B --config | -c
]
[
.B --no-dep | -n
]
[
.B --postprocess | -p
]
.LP
.B action:
[
.B --update|-u
]
[
.B --list   |-l
]
[
.B --clean  |-e
]
[
.B --search |-s
]
[
.B --show   |-w
]
[
.B --install|-i
]
[
.B --build  |-b
]
[
.B --fetch  |-f
]
.SH DESCRIPTION
.B slapt-src
is a utility to make querying, retrieving, and building slackbuilds
as easy as working with binary packages with slapt-get.
.SH OPTIONS
.TP
.B --yes | -y
Do not prompt
.TP
.B --config | -c [configuration file]
Use the specified configuration file instead of /etc/slapt-get/slapt-srcrc
.TP
.B --no-dep | -n
Do not look for dependencies.
.TP
.B --postprocess | -p [command]
Run specified command on generated package after the package is created.  This is handy for transforming packages into SLAX/Linux-Live modules using the various *2lzm utilities.
.SH ACTIONS
.TP
.B --update|-u
Update the local cache of remote slackbuilds.
.TP
.B --list|-l
List available slackbuilds from enabled remote slackbuild sources.
.TP
.B --clean|-e
Clean out the build directories for prior built slackbuilds.
.TP
.B --search|-s [expression(s)]
Search available slackbuilds from enabled remote slackbuild sources.
.TP
.B --show|-w [expression(s)]
Show information about specified slackbuilds.
.TP
.B --install|-i [expression(s)]
Fetch, build, and install the specified slackbuild(s).  The named slackbuild can be postfixed by a colon followed by a version string to specify the exact version if multiple versions are available.  For example, given foo-1.0 and foo-1.2, specifying foo:1.2 specifies the preference for the later.
.TP
.B --build|-b [expression(s)]
Only fetch and build the specified slackbuild(s).
.TP
.B --fetch|-f [expression(s)]
Only fetch the specified slackbuild(s).
.SH CONFIGURATION

.B slapt-src
checks The configuration file
.B /etc/slapt-get/slapt-srcrc
for options and slackbuild locations.

Each slackbuild location is defined with a a 
.B SOURCE
token.

The default package file extension is defined by specifying the
.B PKGEXT
token.

The default package tag can be set by specifying the
.B PKGTAG
token.

An example configuration file may look like this:
.nf
# sample slapt-getrc
SOURCE=http://www.slackware.org.uk/html/slapt-src/slackbuilds.org/13.1/
BUILDDIR=/tmp
PKGEXT=txz
PKGTAG=me
.fi



.SH AUTHOR
Jason Woodward <woodwardj@jaos.org>
.SH "SEE ALSO"
.BR installpkg(8),
.BR makepkg(8),
.BR pkgtool(8), 
.BR upgradepkg(8),
.BR slapt-get(8)
